# Generated by Django 3.0.5 on 2020-04-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='about',
            field=models.CharField(max_length=1000),
        ),
    ]
