# Generated by Django 3.0.5 on 2020-04-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_pizza_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='about',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_url',
            field=models.URLField(default='https://www.igdb.com/games'),
        ),
        migrations.AddField(
            model_name='game',
            name='popularity',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=500000),
        ),
    ]
