# Generated by Django 3.0.5 on 2020-04-21 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200420_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alpha_channel', models.BooleanField(default=False)),
                ('animated', models.BooleanField(default=False)),
                ('height', models.IntegerField()),
                ('image_id', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('width', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cover_id', to='games.Game')),
            ],
        ),
    ]
